// <auto-generated />
using System;
using FDLsys.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FDLsys.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("FDLsys.Equipe", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FlightId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FlightId1")
                        .HasColumnType("int");

                    b.Property<string>("cle")
                        .IsRequired()
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("first_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("fonction")
                        .HasColumnType("int");

                    b.Property<string>("last_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("FlightId1");

                    b.ToTable("Equipes");
                });

            modelBuilder.Entity("FDLsys.Flight", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("cie")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("datevol")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("escalARR")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("escalDEP")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Flight");
                });

            modelBuilder.Entity("FDLsys.ListesFDL", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("Edition_number")
                        .HasColumnType("int");

                    b.Property<int>("FDay_desert_time")
                        .HasColumnType("int");

                    b.Property<int>("FDay_time")
                        .HasColumnType("int");

                    b.Property<int>("Fnight_desert_time")
                        .HasColumnType("int");

                    b.Property<int>("Fnight_time")
                        .HasColumnType("int");

                    b.Property<string>("MatriculeId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("airplane_reg")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("captain_remarks")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("deadhead")
                        .HasColumnType("int");

                    b.Property<int>("month")
                        .HasColumnType("int");

                    b.Property<int>("total_airborn")
                        .HasColumnType("int");

                    b.Property<int>("total_block")
                        .HasColumnType("int");

                    b.Property<short>("validation")
                        .HasColumnType("smallint");

                    b.Property<int>("year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("listesfdl");
                });

            modelBuilder.Entity("FDLsys.Sequences", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("FlightId")
                        .HasColumnType("int");

                    b.Property<int>("ab_off_hour")
                        .HasColumnType("int");

                    b.Property<int>("ab_off_minute")
                        .HasColumnType("int");

                    b.Property<int>("ab_on_hour")
                        .HasColumnType("int");

                    b.Property<int>("ab_on_minute")
                        .HasColumnType("int");

                    b.Property<float>("added_fuel")
                        .HasColumnType("real");

                    b.Property<int>("airborn_time")
                        .HasColumnType("int");

                    b.Property<int>("block_time")
                        .HasColumnType("int");

                    b.Property<int>("bt_in_hour")
                        .HasColumnType("int");

                    b.Property<int>("bt_in_minute")
                        .HasColumnType("int");

                    b.Property<int>("bt_out_hour")
                        .HasColumnType("int");

                    b.Property<int>("bt_out_minute")
                        .HasColumnType("int");

                    b.Property<string>("expected_dep_time")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("fuel_at_departure")
                        .HasColumnType("real");

                    b.Property<int>("listesfdlID")
                        .HasColumnType("int");

                    b.Property<float>("remaining_fuel")
                        .HasColumnType("real");

                    b.Property<float>("remaining_fuel_from_previous")
                        .HasColumnType("real");

                    b.Property<float>("uplift")
                        .HasColumnType("real");

                    b.Property<float>("used_fuel")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("FlightId");

                    b.HasIndex("listesfdlID");

                    b.ToTable("Sequences");
                });

            modelBuilder.Entity("FDLsys.Users", b =>
                {
                    b.Property<string>("Matricule")
                        .HasColumnType("nvarchar(450)");

                    b.Property<byte[]>("PassworSalt")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("Passwordhash")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Matricule");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("FDLsys.Equipe", b =>
                {
                    b.HasOne("FDLsys.Flight", "Flight")
                        .WithMany()
                        .HasForeignKey("FlightId1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Flight");
                });

            modelBuilder.Entity("FDLsys.Sequences", b =>
                {
                    b.HasOne("FDLsys.Flight", "Flight")
                        .WithMany()
                        .HasForeignKey("FlightId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FDLsys.ListesFDL", "listefdl")
                        .WithMany("Sequences")
                        .HasForeignKey("listesfdlID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Flight");

                    b.Navigation("listefdl");
                });

            modelBuilder.Entity("FDLsys.ListesFDL", b =>
                {
                    b.Navigation("Sequences");
                });
#pragma warning restore 612, 618
        }
    }
}
